services:
  - type: web_service
    name: qa-job-scraper-node
    repo: https://github.com/AtmanTest/qa-job-scraper-node
    branch: main
    autoDeploy: yes
    env: node
    plan: free
    region: oregon
    healthCheckPath: /health
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
